BP_1/Controllers/DomuController.cs
using BP_1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BP_1.Controllers
{
    public class DomuController : Controller
    {
        private readonly ILogger<DomuController> _logger;

        public DomuController(ILogger<DomuController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BP_1/Controllers/UživatelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BP_1.Data;
using BP_1.Models;
using Microsoft.AspNetCore.Authorization;

namespace BP_1.Controllers
{
    public class UživatelController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UživatelController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Uživatel
        public async Task<IActionResult> Index()
        {
              return _context.Uživatel != null ? 
                          View(await _context.Uživatel.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Uživatel'  is null.");
        }

        // GET: Uživatel/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Uživatel == null)
            {
                return NotFound();
            }

            var uživatel = await _context.Uživatel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (uživatel == null)
            {
                return NotFound();
            }

            return View(uživatel);
        }

        // GET: Uživatel/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Uživatel/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Jméno,Přijmení,Věk,Výška,Váha,Id1")] Uživatel uživatel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(uživatel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(uživatel);
        }

        // GET: Uživatel/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Uživatel == null)
            {
                return NotFound();
            }

            var uživatel = await _context.Uživatel.FindAsync(id);
            if (uživatel == null)
            {
                return NotFound();
            }
            return View(uživatel);
        }

        // POST: Uživatel/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Jméno,Přijmení,Věk,Výška,Váha,Id1")] Uživatel uživatel)
        {
            if (id != uživatel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(uživatel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UživatelExists(uživatel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(uživatel);
        }

        // GET: Uživatel/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Uživatel == null)
            {
                return NotFound();
            }

            var uživatel = await _context.Uživatel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (uživatel == null)
            {
                return NotFound();
            }

            return View(uživatel);
        }

        // POST: Uživatel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Uživatel == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Uživatel'  is null.");
            }
            var uživatel = await _context.Uživatel.FindAsync(id);
            if (uživatel != null)
            {
                _context.Uživatel.Remove(uživatel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UživatelExists(int id)
        {
          return (_context.Uživatel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BP_1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BP_0.1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BP_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

        @if (SignInManager.IsSignedIn(User))
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Domu" asp-action="Index">BP_1</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Domu" asp-action="Index">Domů</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Uživatel" asp-action="Index">Uživatel</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Uživatel" asp-action="Index">Současný TP</a> <!--<a href="/"UPRAVIT</a> -->
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Uživatel" asp-action="Index">Souhrny</a>  <!--<a href="/"UPRAVIT</a> -->
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Uživatel" asp-action="Index">Síň slávy</a>  <!--<a href="/"UPRAVIT</a> -->
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Domu" asp-action="Privacy">Ochranu osobních údajů</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        }
        else 
        {
            var currentPage = Context.Request.Path;
            if (currentPage == "/")
            {
                
                <nav class = "navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> @*style="float:right"*@
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end mx-3">
                            

                                <partial name="_LoginPartial" />
                           
                                         
                    
                    </div>
                </nav>
            }
        }
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Jiří Mlčoušek - <a asp-area="" asp-controller="Domu" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>